using FluentAssertions;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TeejoshSystem.Infrastructure.Adapters.Outbound.Persistence;
using TeejoshSystem.Migrations.PostgreSql;
using TeejoshSystem.Migrations.Sqlite;
using Xunit;

namespace TeejoshSystem.Infrastructure.Tests.Migrations;

public sealed class ProviderMigrationTests
{
    [Fact]
    public async Task Sqlite_MigratesEmptyDatabaseToCurrentSchema()
    {
        var path = Path.Combine(Path.GetTempPath(), $"teejosh-sqlite-{Guid.NewGuid():N}.db");
        try
        {
            var options = new DbContextOptionsBuilder<InventarioDbContext>()
                .UseSqlite($"Data Source={path}", provider => provider.MigrationsAssembly(
                    typeof(SqliteDesignTimeDbContextFactory).Assembly.GetName().Name))
                .Options;

            await using var context = new InventarioDbContext(options);
            (await context.Database.GetAppliedMigrationsAsync()).Should().BeEmpty();
            await context.Database.MigrateAsync();
            (await context.Database.GetPendingMigrationsAsync()).Should().BeEmpty();

            await using var connection = new SqliteConnection($"Data Source={path}");
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = "SELECT name FROM sqlite_master WHERE type='table'";
            var tables = new List<string>();
            await using (var reader = await command.ExecuteReaderAsync())
            {
                while (await reader.ReadAsync()) tables.Add(reader.GetString(0));
            }
            tables.Should().Contain(new[] { "product", "sale", "sale_detail", "app_user", "__EFMigrationsHistory" });

            command.CommandText = "SELECT COUNT(*) FROM pragma_table_info('hot_wheels') WHERE name = 'Discriminator'";
            var discriminatorColumns = Convert.ToInt32(await command.ExecuteScalarAsync());
            discriminatorColumns.Should().Be(0);
        }
        finally
        {
            SqliteConnection.ClearAllPools();
            if (File.Exists(path)) File.Delete(path);
        }
    }

    [Fact]
    public void PostgreSql_ProducesCompleteIdempotentScriptFromEmptyDatabase()
    {
        var options = new DbContextOptionsBuilder<InventarioDbContext>()
            .UseNpgsql(
                "Host=localhost;Database=teejosh_script_only;Username=postgres;Password=postgres",
                provider => provider.MigrationsAssembly(
                    typeof(PostgreSqlDesignTimeDbContextFactory).Assembly.GetName().Name))
            .Options;

        using var context = new InventarioDbContext(options);
        var script = context.GetService<IMigrator>().GenerateScript(
            fromMigration: null,
            toMigration: null,
            MigrationsSqlGenerationOptions.Idempotent);

        script.Should().Contain("CREATE TABLE product");
        script.Should().Contain("CREATE TABLE sale");
        script.Should().Contain("CREATE TABLE sale_detail");
        script.Should().Contain("CREATE TABLE app_user");
        script.Should().Contain("GENERATED BY DEFAULT AS IDENTITY");
        script.Should().Contain("__EFMigrationsHistory");
    }

    [Fact]
    public void Providers_HaveIndependentMigrationAssembliesAndSnapshots()
    {
        ReferenceEquals(typeof(SqliteDesignTimeDbContextFactory).Assembly,
            typeof(PostgreSqlDesignTimeDbContextFactory).Assembly).Should().BeFalse();
        typeof(SqliteDesignTimeDbContextFactory).Assembly.GetTypes()
            .Should().Contain(type => typeof(Migration).IsAssignableFrom(type));
        typeof(PostgreSqlDesignTimeDbContextFactory).Assembly.GetTypes()
            .Should().Contain(type => typeof(Migration).IsAssignableFrom(type));
    }
}
