{
 "title": "S14-Local",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n0.99,\r\nsum(rate(teejosh_sale_duration_seconds_bucket[5m])) by (le)\r\n)"
    }
   ]
  },
  {
   "title": "teejosh_product_deleted_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "teejosh_product_deleted_total" }
   ]
  },
  {
   "title": "teejosh_product_created_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "teejosh_product_created_total" }
   ]
  },
  {
   "title": "teejosh_sale_failure_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "teejosh_sale_failure_total" }
   ]
  },
  {
   "title": "teejosh_sale_success_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "teejosh_sale_success_total" }
   ]
  },
  {
   "title": "teejosh_login_failure_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "teejosh_login_failure_total" }
   ]
  },
  {
   "title": "teejosh_login_success_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "teejosh_login_success_total" }
   ]
  }
 ]
}