CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE app_user (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        rol text NOT NULL,
        username character varying(100) NOT NULL,
        password_hash character varying(60) NOT NULL,
        active boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_app_user" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE audit_log (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        timestamp timestamp with time zone NOT NULL,
        usuario character varying(100),
        entidad character varying(100) NOT NULL,
        entidad_id character varying(50) NOT NULL,
        accion character varying(20) NOT NULL,
        cambios TEXT,
        CONSTRAINT "PK_audit_log" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE funko_special_feature (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        CONSTRAINT "PK_funko_special_feature" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE funko_subtype (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        CONSTRAINT "PK_funko_subtype" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE hot_wheels_category (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        CONSTRAINT "PK_hot_wheels_category" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE product (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        type text NOT NULL,
        name character varying(50) NOT NULL,
        price numeric(10,2) NOT NULL,
        units integer NOT NULL,
        image_path text,
        CONSTRAINT "PK_product" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE sale (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        date timestamp with time zone NOT NULL,
        total numeric(10,2) NOT NULL,
        CONSTRAINT "PK_sale" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE sync_outbox (
        id uuid NOT NULL,
        operation_type character varying(10) NOT NULL,
        entity_table character varying(50) NOT NULL,
        entity_id integer,
        payload_json text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        device_id character varying(100) NOT NULL,
        retry_count integer NOT NULL DEFAULT 0,
        last_error text,
        CONSTRAINT "PK_sync_outbox" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE tcg_expansion (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        "FranquiciaId" integer NOT NULL,
        image_url text,
        CONSTRAINT "PK_tcg_expansion" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE tcg_franchise (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        CONSTRAINT "PK_tcg_franchise" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE tcg_pack (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        "FranquiciaId" integer NOT NULL,
        CONSTRAINT "PK_tcg_pack" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE funko (
        product_id integer NOT NULL,
        box_number integer NOT NULL,
        license character varying(100) NOT NULL,
        subtype integer NOT NULL,
        special_caracteristic integer NOT NULL,
        "Discriminator" text,
        CONSTRAINT "PK_funko" PRIMARY KEY (product_id),
        CONSTRAINT "FK_funko_product_product_id" FOREIGN KEY (product_id) REFERENCES product ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE hot_wheels (
        product_id integer NOT NULL,
        model character varying(100) NOT NULL,
        year integer NOT NULL,
        serie character varying(100) NOT NULL,
        category_id integer NOT NULL,
        "Discriminator" text,
        CONSTRAINT "PK_hot_wheels" PRIMARY KEY (product_id),
        CONSTRAINT "FK_hot_wheels_product_product_id" FOREIGN KEY (product_id) REFERENCES product ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE tcg (
        product_id integer NOT NULL,
        pack_id integer NOT NULL,
        expansion_id integer NOT NULL,
        "Discriminator" text,
        CONSTRAINT "PK_tcg" PRIMARY KEY (product_id),
        CONSTRAINT "FK_tcg_product_product_id" FOREIGN KEY (product_id) REFERENCES product ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE toy (
        product_id integer NOT NULL,
        min_years_old integer NOT NULL,
        min_players integer NOT NULL,
        max_players integer NOT NULL,
        is_board_game boolean NOT NULL,
        "Discriminator" text,
        CONSTRAINT "PK_toy" PRIMARY KEY (product_id),
        CONSTRAINT check_players CHECK (max_players >= min_players),
        CONSTRAINT "FK_toy_product_product_id" FOREIGN KEY (product_id) REFERENCES product ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE varios (
        product_id integer NOT NULL,
        brand character varying(100) NOT NULL,
        height numeric(10,2) NOT NULL,
        width numeric(10,2) NOT NULL,
        length numeric(10,2),
        material character varying(100) NOT NULL,
        ilustration boolean NOT NULL,
        "Discriminator" text,
        CONSTRAINT "PK_varios" PRIMARY KEY (product_id),
        CONSTRAINT check_dimensions CHECK (height > 0 AND width > 0 AND (length IS NULL OR length > 0)),
        CONSTRAINT "FK_varios_product_product_id" FOREIGN KEY (product_id) REFERENCES product ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE TABLE sale_detail (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        sale_id integer NOT NULL,
        product_id integer NOT NULL,
        product_name character varying(100) NOT NULL,
        quantity integer NOT NULL,
        unit_price numeric(10,2) NOT NULL,
        CONSTRAINT "PK_sale_detail" PRIMARY KEY (id),
        CONSTRAINT "FK_sale_detail_sale_sale_id" FOREIGN KEY (sale_id) REFERENCES sale (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    INSERT INTO funko_special_feature (id, name)
    VALUES (1, 'Chase');
    INSERT INTO funko_special_feature (id, name)
    VALUES (2, 'Glow in the Dark');
    INSERT INTO funko_special_feature (id, name)
    VALUES (3, 'Flocked');
    INSERT INTO funko_special_feature (id, name)
    VALUES (4, 'Metallic');
    INSERT INTO funko_special_feature (id, name)
    VALUES (5, 'Diamond / Glitter');
    INSERT INTO funko_special_feature (id, name)
    VALUES (6, 'Black Light');
    INSERT INTO funko_special_feature (id, name)
    VALUES (7, 'Chrome');
    INSERT INTO funko_special_feature (id, name)
    VALUES (8, 'Translucent');
    INSERT INTO funko_special_feature (id, name)
    VALUES (9, 'Exclusivo');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    INSERT INTO funko_subtype (id, name)
    VALUES (1, 'Pop! Vinyl');
    INSERT INTO funko_subtype (id, name)
    VALUES (2, 'Pop! Deluxe');
    INSERT INTO funko_subtype (id, name)
    VALUES (3, 'Pop! Super');
    INSERT INTO funko_subtype (id, name)
    VALUES (4, 'Pop! Mega');
    INSERT INTO funko_subtype (id, name)
    VALUES (5, 'Pop! Rides');
    INSERT INTO funko_subtype (id, name)
    VALUES (6, 'Pop! Moments');
    INSERT INTO funko_subtype (id, name)
    VALUES (7, 'Pop! Albums');
    INSERT INTO funko_subtype (id, name)
    VALUES (8, 'Bitty Pop!');
    INSERT INTO funko_subtype (id, name)
    VALUES (9, 'Funko Soda');
    INSERT INTO funko_subtype (id, name)
    VALUES (10, 'Mystery Minis');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    INSERT INTO hot_wheels_category (id, name)
    VALUES (1, 'Basic Car');
    INSERT INTO hot_wheels_category (id, name)
    VALUES (2, 'Treasure Hunt');
    INSERT INTO hot_wheels_category (id, name)
    VALUES (3, 'Super Treasure Hunt');
    INSERT INTO hot_wheels_category (id, name)
    VALUES (4, 'Car Culture');
    INSERT INTO hot_wheels_category (id, name)
    VALUES (5, 'Premium');
    INSERT INTO hot_wheels_category (id, name)
    VALUES (6, 'Boulevard');
    INSERT INTO hot_wheels_category (id, name)
    VALUES (7, 'Pop Culture');
    INSERT INTO hot_wheels_category (id, name)
    VALUES (8, 'Team Transport');
    INSERT INTO hot_wheels_category (id, name)
    VALUES (9, 'Mystery Models');
    INSERT INTO hot_wheels_category (id, name)
    VALUES (10, 'HWC / RLC');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (1, 1, NULL, 'Escarlata y Púrpura Base');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (2, 1, NULL, '151');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (3, 1, NULL, 'Obsidiana Llameante');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (4, 1, NULL, 'Destinos de Paldea');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (5, 1, NULL, 'Fuerza Temporal');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (6, 2, NULL, 'Legendary Collection');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (7, 2, NULL, 'Age of Overlord');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (8, 2, NULL, 'Phantom Nightmare');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (9, 3, NULL, 'Wilds of Eldraine');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (10, 3, NULL, 'The Lost Caverns of Ixalan');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (11, 3, NULL, 'Murders at Karlov Manor');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (12, 4, NULL, 'Romance Dawn');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (13, 4, NULL, 'Paramount War');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (14, 4, NULL, 'Pillars of Strength');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (15, 4, NULL, 'Kingdoms of Intrigue');
    INSERT INTO tcg_expansion (id, "FranquiciaId", image_url, name)
    VALUES (16, 5, NULL, 'Serie Base');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    INSERT INTO tcg_franchise (id, name)
    VALUES (1, 'Pokémon');
    INSERT INTO tcg_franchise (id, name)
    VALUES (2, 'Yu-Gi-Oh!');
    INSERT INTO tcg_franchise (id, name)
    VALUES (3, 'Magic: The Gathering');
    INSERT INTO tcg_franchise (id, name)
    VALUES (4, 'One Piece');
    INSERT INTO tcg_franchise (id, name)
    VALUES (5, 'Bluey');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (1, 1, 'Sobre Individual');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (2, 1, 'Blister 3 Sobres');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (3, 1, 'Elite Trainer Box');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (4, 1, 'Caja de 36 Sobres');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (5, 1, 'Colección Premium');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (6, 2, 'Sobre Individual');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (7, 2, 'Caja de 24 Sobres');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (8, 2, 'Structure Deck');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (9, 3, 'Draft Booster');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (10, 3, 'Set Booster');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (11, 3, 'Collector Booster');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (12, 3, 'Bundle');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (13, 4, 'Sobre Individual');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (14, 4, 'Caja de 24 Sobres');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (15, 4, 'Starter Deck');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (16, 5, 'Sobre Individual');
    INSERT INTO tcg_pack (id, "FranquiciaId", name)
    VALUES (17, 5, 'Starter Pack');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_app_user_username" ON app_user (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE INDEX "IX_audit_log_entidad_entidad_id" ON audit_log (entidad, entidad_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE INDEX "IX_audit_log_timestamp" ON audit_log (timestamp);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_funko_special_feature_name" ON funko_special_feature (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_funko_subtype_name" ON funko_subtype (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_hot_wheels_category_name" ON hot_wheels_category (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE INDEX "IX_sale_detail_sale_id" ON sale_detail (sale_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE INDEX idx_outbox_created_at ON sync_outbox (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tcg_expansion_name_FranquiciaId" ON tcg_expansion (name, "FranquiciaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tcg_franchise_name" ON tcg_franchise (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_tcg_pack_name_FranquiciaId" ON tcg_pack (name, "FranquiciaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('funko_special_feature', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM funko_special_feature) + 1,
            nextval(pg_get_serial_sequence('funko_special_feature', 'id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('funko_subtype', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM funko_subtype) + 1,
            nextval(pg_get_serial_sequence('funko_subtype', 'id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('hot_wheels_category', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM hot_wheels_category) + 1,
            nextval(pg_get_serial_sequence('hot_wheels_category', 'id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('tcg_expansion', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM tcg_expansion) + 1,
            nextval(pg_get_serial_sequence('tcg_expansion', 'id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('tcg_franchise', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM tcg_franchise) + 1,
            nextval(pg_get_serial_sequence('tcg_franchise', 'id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('tcg_pack', 'id'),
        GREATEST(
            (SELECT MAX(id) FROM tcg_pack) + 1,
            nextval(pg_get_serial_sequence('tcg_pack', 'id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260713205213_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260713205213_InitialCreate', '8.0.0');
    END IF;
END $EF$;
COMMIT;

