// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeejoshSystem.Infrastructure.Adapters.Outbound.Persistence;

#nullable disable

namespace TeejoshSystem.Infrastructure.Adapters.Outbound.Persistence.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    [Migration("20260508020024_AddAppUserTable")]
    partial class AddAppUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Catalogos.FunkoCaracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("funko_special_feature", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Chase"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Glow in the Dark"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Flocked"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Metallic"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Diamond / Glitter"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Black Light"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Chrome"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Translucent"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Exclusivo"
                        });
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Catalogos.FunkoSubtipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("funko_subtype", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pop! Vinyl"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Pop! Deluxe"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Pop! Super"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Pop! Mega"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Pop! Rides"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Pop! Moments"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Pop! Albums"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Bitty Pop!"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Funko Soda"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Mystery Minis"
                        });
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Catalogos.HotWheelsCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("hot_wheels_category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Basic Car"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Treasure Hunt"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Super Treasure Hunt"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Car Culture"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Premium"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Boulevard"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Pop Culture"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Team Transport"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Mystery Models"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "HWC / RLC"
                        });
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Catalogos.TcgExpansion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("FranquiciaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Nombre", "FranquiciaId")
                        .IsUnique();

                    b.ToTable("tcg_expansion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FranquiciaId = 1,
                            Nombre = "Escarlata y Púrpura Base"
                        },
                        new
                        {
                            Id = 2,
                            FranquiciaId = 1,
                            Nombre = "151"
                        },
                        new
                        {
                            Id = 3,
                            FranquiciaId = 1,
                            Nombre = "Obsidiana Llameante"
                        },
                        new
                        {
                            Id = 4,
                            FranquiciaId = 1,
                            Nombre = "Destinos de Paldea"
                        },
                        new
                        {
                            Id = 5,
                            FranquiciaId = 1,
                            Nombre = "Fuerza Temporal"
                        },
                        new
                        {
                            Id = 6,
                            FranquiciaId = 2,
                            Nombre = "Legendary Collection"
                        },
                        new
                        {
                            Id = 7,
                            FranquiciaId = 2,
                            Nombre = "Age of Overlord"
                        },
                        new
                        {
                            Id = 8,
                            FranquiciaId = 2,
                            Nombre = "Phantom Nightmare"
                        },
                        new
                        {
                            Id = 9,
                            FranquiciaId = 3,
                            Nombre = "Wilds of Eldraine"
                        },
                        new
                        {
                            Id = 10,
                            FranquiciaId = 3,
                            Nombre = "The Lost Caverns of Ixalan"
                        },
                        new
                        {
                            Id = 11,
                            FranquiciaId = 3,
                            Nombre = "Murders at Karlov Manor"
                        },
                        new
                        {
                            Id = 12,
                            FranquiciaId = 4,
                            Nombre = "Romance Dawn"
                        },
                        new
                        {
                            Id = 13,
                            FranquiciaId = 4,
                            Nombre = "Paramount War"
                        },
                        new
                        {
                            Id = 14,
                            FranquiciaId = 4,
                            Nombre = "Pillars of Strength"
                        },
                        new
                        {
                            Id = 15,
                            FranquiciaId = 4,
                            Nombre = "Kingdoms of Intrigue"
                        },
                        new
                        {
                            Id = 16,
                            FranquiciaId = 5,
                            Nombre = "Serie Base"
                        });
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Catalogos.TcgFranquicia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tcg_franchise", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pokémon"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Yu-Gi-Oh!"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Magic: The Gathering"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "One Piece"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Bluey"
                        });
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Catalogos.TcgPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("FranquiciaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Nombre", "FranquiciaId")
                        .IsUnique();

                    b.ToTable("tcg_pack", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FranquiciaId = 1,
                            Nombre = "Sobre Individual"
                        },
                        new
                        {
                            Id = 2,
                            FranquiciaId = 1,
                            Nombre = "Blister 3 Sobres"
                        },
                        new
                        {
                            Id = 3,
                            FranquiciaId = 1,
                            Nombre = "Elite Trainer Box"
                        },
                        new
                        {
                            Id = 4,
                            FranquiciaId = 1,
                            Nombre = "Caja de 36 Sobres"
                        },
                        new
                        {
                            Id = 5,
                            FranquiciaId = 1,
                            Nombre = "Colección Premium"
                        },
                        new
                        {
                            Id = 6,
                            FranquiciaId = 2,
                            Nombre = "Sobre Individual"
                        },
                        new
                        {
                            Id = 7,
                            FranquiciaId = 2,
                            Nombre = "Caja de 24 Sobres"
                        },
                        new
                        {
                            Id = 8,
                            FranquiciaId = 2,
                            Nombre = "Structure Deck"
                        },
                        new
                        {
                            Id = 9,
                            FranquiciaId = 3,
                            Nombre = "Draft Booster"
                        },
                        new
                        {
                            Id = 10,
                            FranquiciaId = 3,
                            Nombre = "Set Booster"
                        },
                        new
                        {
                            Id = 11,
                            FranquiciaId = 3,
                            Nombre = "Collector Booster"
                        },
                        new
                        {
                            Id = 12,
                            FranquiciaId = 3,
                            Nombre = "Bundle"
                        },
                        new
                        {
                            Id = 13,
                            FranquiciaId = 4,
                            Nombre = "Sobre Individual"
                        },
                        new
                        {
                            Id = 14,
                            FranquiciaId = 4,
                            Nombre = "Caja de 24 Sobres"
                        },
                        new
                        {
                            Id = 15,
                            FranquiciaId = 4,
                            Nombre = "Starter Deck"
                        },
                        new
                        {
                            Id = 16,
                            FranquiciaId = 5,
                            Nombre = "Sobre Individual"
                        },
                        new
                        {
                            Id = 17,
                            FranquiciaId = 5,
                            Nombre = "Starter Pack"
                        });
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.FunkoDetalle", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int?>("CaracteristicaEspecialId")
                        .IsRequired()
                        .HasColumnType("INTEGER")
                        .HasColumnName("special_caracteristic");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("license");

                    b.Property<int>("NumeroCaja")
                        .HasColumnType("INTEGER")
                        .HasColumnName("box_number");

                    b.Property<int>("SubtipoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subtype");

                    b.HasKey("ProductoId");

                    b.ToTable("funko", (string)null);

                    b.HasDiscriminator().HasValue("FunkoDetalle");
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.HotWheelsDetalle", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("serie");

                    b.HasKey("ProductoId");

                    b.ToTable("hot_wheels", (string)null);

                    b.HasDiscriminator().HasValue("HotWheelsDetalle");
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.TcgDetalle", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("ExpansionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expansion_id");

                    b.Property<int>("PackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pack_id");

                    b.HasKey("ProductoId");

                    b.ToTable("tcg", (string)null);

                    b.HasDiscriminator().HasValue("TcgDetalle");
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.ToyDetalle", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("EdadMinima")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_years_old");

                    b.Property<bool>("EsJuegoDeMesa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_board_game");

                    b.Property<int>("JugadoresMax")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_players");

                    b.Property<int>("JugadoresMin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_players");

                    b.HasKey("ProductoId");

                    b.ToTable("toy", null, t =>
                        {
                            t.HasCheckConstraint("check_players", "max_players >= min_players");
                        });

                    b.HasDiscriminator().HasValue("ToyDetalle");
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.VariosDetalle", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Alto")
                        .HasColumnType("TEXT")
                        .HasColumnName("height");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("TEXT")
                        .HasColumnName("width");

                    b.Property<decimal?>("Largo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("length");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("brand");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("material");

                    b.Property<bool>("TieneIlustracion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ilustration");

                    b.HasKey("ProductoId");

                    b.ToTable("varios", null, t =>
                        {
                            t.HasCheckConstraint("check_dimensions", "height > 0 AND width > 0 AND (length IS NULL OR length > 0)");
                        });

                    b.HasDiscriminator().HasValue("VariosDetalle");
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.VentaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_price");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sale_id");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("sale_detail", (string)null);
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("sale", (string)null);
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.FunkoDetalle", b =>
                {
                    b.HasOne("TeejoshSystem.Domain.Entities.Producto", null)
                        .WithOne()
                        .HasForeignKey("TeejoshSystem.Domain.Entities.Detalles.FunkoDetalle", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.HotWheelsDetalle", b =>
                {
                    b.HasOne("TeejoshSystem.Domain.Entities.Producto", null)
                        .WithOne()
                        .HasForeignKey("TeejoshSystem.Domain.Entities.Detalles.HotWheelsDetalle", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.TcgDetalle", b =>
                {
                    b.HasOne("TeejoshSystem.Domain.Entities.Producto", null)
                        .WithOne()
                        .HasForeignKey("TeejoshSystem.Domain.Entities.Detalles.TcgDetalle", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.ToyDetalle", b =>
                {
                    b.HasOne("TeejoshSystem.Domain.Entities.Producto", null)
                        .WithOne()
                        .HasForeignKey("TeejoshSystem.Domain.Entities.Detalles.ToyDetalle", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.VariosDetalle", b =>
                {
                    b.HasOne("TeejoshSystem.Domain.Entities.Producto", null)
                        .WithOne()
                        .HasForeignKey("TeejoshSystem.Domain.Entities.Detalles.VariosDetalle", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.VentaDetalle", b =>
                {
                    b.HasOne("TeejoshSystem.Domain.Entities.Venta", null)
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Producto", b =>
                {
                    b.OwnsOne("TeejoshSystem.Domain.ValueObjects.NombreProducto", "Nombre", b1 =>
                        {
                            b1.Property<int>("ProductoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.HasKey("ProductoId");

                            b1.ToTable("product");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.OwnsOne("TeejoshSystem.Domain.ValueObjects.Precio", "Precio", b1 =>
                        {
                            b1.Property<int>("ProductoId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("price");

                            b1.HasKey("ProductoId");

                            b1.ToTable("product");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.OwnsOne("TeejoshSystem.Domain.ValueObjects.Unidades", "Stock", b1 =>
                        {
                            b1.Property<int>("ProductoId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("units");

                            b1.HasKey("ProductoId");

                            b1.ToTable("product");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.Navigation("Nombre")
                        .IsRequired();

                    b.Navigation("Precio")
                        .IsRequired();

                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
