// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeejoshSystem.Infrastructure.Adapters.Outbound.Persistence;

#nullable disable

namespace TeejoshSystem.Infrastructure.Adapters.Outbound.Persistence.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    partial class InventarioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Catalogos.FunkoCaracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("funko_special_feature", (string)null);
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Catalogos.FunkoSubtipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("funko_subtype", (string)null);
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Catalogos.HotWheelsCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("hot_wheels_category", (string)null);
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Catalogos.TcgExpansion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("FranquiciaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tcg_expansion", (string)null);
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Catalogos.TcgFranquicia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tcg_franchise", (string)null);
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Catalogos.TcgPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("FranquiciaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tcg_pack", (string)null);
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.FunkoDetalle", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int?>("CaracteristicaEspecialId")
                        .IsRequired()
                        .HasColumnType("INTEGER")
                        .HasColumnName("special_caracteristic");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("license");

                    b.Property<int>("NumeroCaja")
                        .HasColumnType("INTEGER")
                        .HasColumnName("box_number");

                    b.Property<int>("SubtipoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subtype");

                    b.HasKey("ProductoId");

                    b.ToTable("funko", (string)null);

                    b.HasDiscriminator().HasValue("FunkoDetalle");
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.HotWheelsDetalle", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("serie");

                    b.HasKey("ProductoId");

                    b.ToTable("hot_wheels", (string)null);

                    b.HasDiscriminator().HasValue("HotWheelsDetalle");
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.TcgDetalle", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("ExpansionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("expansion_id");

                    b.Property<int>("PackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pack_id");

                    b.HasKey("ProductoId");

                    b.ToTable("tcg", (string)null);

                    b.HasDiscriminator().HasValue("TcgDetalle");
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.ToyDetalle", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("EdadMinima")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_years_old");

                    b.Property<bool>("EsJuegoDeMesa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_board_game");

                    b.Property<int>("JugadoresMax")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_players");

                    b.Property<int>("JugadoresMin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_players");

                    b.HasKey("ProductoId");

                    b.ToTable("toy", (string)null);

                    b.HasDiscriminator().HasValue("ToyDetalle");
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.VariosDetalle", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Alto")
                        .HasColumnType("TEXT")
                        .HasColumnName("height");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("TEXT")
                        .HasColumnName("width");

                    b.Property<decimal?>("Largo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("length");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("brand");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("material");

                    b.Property<bool>("TieneIlustracion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ilustration");

                    b.HasKey("ProductoId");

                    b.ToTable("varios", (string)null);

                    b.HasDiscriminator().HasValue("VariosDetalle");
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.FunkoDetalle", b =>
                {
                    b.HasOne("TeejoshSystem.Domain.Entities.Producto", null)
                        .WithOne()
                        .HasForeignKey("TeejoshSystem.Domain.Entities.Detalles.FunkoDetalle", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.HotWheelsDetalle", b =>
                {
                    b.HasOne("TeejoshSystem.Domain.Entities.Producto", null)
                        .WithOne()
                        .HasForeignKey("TeejoshSystem.Domain.Entities.Detalles.HotWheelsDetalle", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.TcgDetalle", b =>
                {
                    b.HasOne("TeejoshSystem.Domain.Entities.Producto", null)
                        .WithOne()
                        .HasForeignKey("TeejoshSystem.Domain.Entities.Detalles.TcgDetalle", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.ToyDetalle", b =>
                {
                    b.HasOne("TeejoshSystem.Domain.Entities.Producto", null)
                        .WithOne()
                        .HasForeignKey("TeejoshSystem.Domain.Entities.Detalles.ToyDetalle", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Detalles.VariosDetalle", b =>
                {
                    b.HasOne("TeejoshSystem.Domain.Entities.Producto", null)
                        .WithOne()
                        .HasForeignKey("TeejoshSystem.Domain.Entities.Detalles.VariosDetalle", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeejoshSystem.Domain.Entities.Producto", b =>
                {
                    b.OwnsOne("TeejoshSystem.Domain.ValueObjects.NombreProducto", "Nombre", b1 =>
                        {
                            b1.Property<int>("ProductoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("name");

                            b1.HasKey("ProductoId");

                            b1.ToTable("product");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.OwnsOne("TeejoshSystem.Domain.ValueObjects.Precio", "Precio", b1 =>
                        {
                            b1.Property<int>("ProductoId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("price");

                            b1.HasKey("ProductoId");

                            b1.ToTable("product");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.OwnsOne("TeejoshSystem.Domain.ValueObjects.Unidades", "Stock", b1 =>
                        {
                            b1.Property<int>("ProductoId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("units");

                            b1.HasKey("ProductoId");

                            b1.ToTable("product");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.Navigation("Nombre")
                        .IsRequired();

                    b.Navigation("Precio")
                        .IsRequired();

                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
